"""empty message

Revision ID: d32096924d03
Revises: 
Create Date: 2020-04-04 11:32:31.461371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd32096924d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserAppointments', sa.Column('visitor_email', sa.String(length=80), nullable=True))
    op.add_column('UserAppointments', sa.Column('visitor_name', sa.String(length=20), nullable=True))
    op.add_column('UserAppointments', sa.Column('visitor_phone_number', sa.Integer(), nullable=True))
    op.alter_column('UserAppointments', 'UserAccount_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserAppointments', 'UserAccount_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('UserAppointments', 'visitor_phone_number')
    op.drop_column('UserAppointments', 'visitor_name')
    op.drop_column('UserAppointments', 'visitor_email')
    # ### end Alembic commands ###
